devEnv:
  defaultClock: 5
  defaultRounds: 2
  defaultCategory: 'All'
  defaultDifficulty: 'Medium'
  defaultNumberOfAnswers: 5
liveEnv:
  defaultClock: 42
  defaultRounds: 5
  defaultCategory: 'All'
  defaultDifficulty: 'Medium'
  defaultNumberOfAnswers: 5

dev: true
